$script = <<SCRIPT
echo Beginning provisioning...

sudo dnf config-manager --set-enabled {fedora,updates}{,-debuginfo}
sudo dnf config-manager --set-enabled updates-testing{,-debuginfo}

sudo dnf -y distro-sync --downloadonly
sudo dnf -yC distro-sync --nogpgcheck || true

sudo dnf -y install psmisc gdb valgrind git vim emacs-nox tmux systemtap gdb
sudo dnf -y install rxvt-unicode-256color strace nmap ltrace lsof valgrind
sudo dnf -y install krb5-{server,workstation} bind-utils

sudo dnf -y debuginfo-install krb5-{libs,workstation,server}

date > /etc/vagrant_provisioned_at
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "fedora/30-cloud-base"
    config.vm.provision "shell", inline: $script
    config.vm.define "fc30" do |fc30|
        fc30.vm.provider :libvirt do |domain|
            domain.cpus = 4
            domain.graphics_type = "spice"
            domain.memory = 4096
            domain.video_type = "qxl"
            domain.random :model => "random"
            domain.nic_model_type = "rtl8139"
        end
    end
end
