$script = <<SCRIPT
echo Beginning provisioning...

echo -e 'secretes\nsecretes' | passwd vagrant
echo -e 'secretes\nsecretes' | passwd root
sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
systemctl restart sshd

# This image sucks
echo -e "net.ipv6.conf.all.disable_ipv6=0\nnet.ipv6.conf.default.disable_ipv6=0" > /etc/sysctl.conf
sysctl -p

dnf -y install curl
cd /etc/yum.repos.d
rm -rf *
curl -kO http://shell.bos.redhat.com/~rharwood/rhel8.repo
curl -kO https://copr.devel.redhat.com/coprs/rharwood/rhel8-missing/repo/rhel-8.dev/rharwood-rhel8-missing-rhel-8.dev.repo
dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm

dnf -y distro-sync --nogpgcheck

dnf -y install psmisc gdb valgrind git emacs-nox tmux gdb strace nmap ltrace lsof valgrind krb5-{server,workstation} mosh rxvt-unicode-256color wget

date > /etc/vagrant_provisioned_at
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "generic/rhel8"
    config.vm.provision "shell", inline: $script

    config.vm.define "default" do |default|
        default.vm.provider :libvirt do |domain|
            domain.disk_bus = "virtio"
            domain.cpus = 4
            domain.graphics_type = "spice"
            domain.memory = 2048
            domain.video_type = "qxl"
            domain.random :model => "random"
            domain.nic_model_type = "rtl8139"
        end
    end
end
