$pkgs = File.read("../packages").gsub("\n", " ")
$debuginfos = File.read("../debuginfos").gsub("\n", " ")

$script = """
echo Beginning provisioning...

echo -e 'secretes\nsecretes' | passwd vagrant
echo -e 'secretes\nsecretes' | passwd root
sed -i -e 's/PasswordAuthentication no/PasswordAuthentication yes/' \
    -e 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' \
    /etc/ssh/sshd_config
systemctl reload-or-restart sshd

setenforce 0
sed -i 's/SELINUX=\(enforcing\|permissive\)/SELINUX=disabled/g' \
    /etc/selinux/config

dnf config-manager --set-disabled \*
dnf config-manager --set-enabled fedora

dnf -y --downloadonly --nogpgcheck install fedora-repos-rawhide
dnf -Cy install fedora-repos-rawhide

dnf config-manager --set-disabled \*
dnf config-manager --set-enabled rawhide{,-debuginfo}

# mirror failures again, and friggin rawhide...
dnf -y distro-sync --downloadonly --nogpgcheck
dnf -yC distro-sync --nogpgcheck || true

dnf -y install #{$pkgs}
dnf -y debuginfo-install #{$debuginfos}

# This straight up doesn't work
rm -f /etc/profile.d/debuginfod*

date > /etc/vagrant_provisioned_at
"""

Vagrant.configure("2") do |config|
    config.vm.box = "fedora/35-cloud-base"

    config.vm.provision "shell", inline: $script

    config.vm.define "rawhide" do |rawhide|
        rawhide.vm.provider :libvirt do |domain|
            domain.cpus = 4
            domain.graphics_type = "spice"
            domain.memory = 2048
            domain.video_type = "qxl"
            domain.random :model => "random"
            domain.volume_cache = "unsafe"
            domain.nic_model_type = "rtl8139"
        end
    end
end
