$script = <<SCRIPT
echo Beginning provisioning...

echo -e 'secretes\nsecretes' | passwd vagrant
sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' \
    /etc/ssh/sshd_config
sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' \
    /etc/ssh/sshd_config
echo -e 'secretes\nsecretes' | passwd root
systemctl restart sshd

setenforce 0
sed -i 's/SELINUX=\(enforcing\|permissive\)/SELINUX=disabled/g' \
    /etc/selinux/config

dnf config-manager --set-disabled \*
dnf config-manager --set-enabled fedora

dnf -y --downloadonly --nogpgcheck install fedora-repos-rawhide
dnf -Cy install fedora-repos-rawhide

dnf config-manager --set-disabled \*
dnf config-manager --set-enabled rawhide{,-debuginfo}

# mirror failures again, and friggin rawhide...
dnf -y distro-sync --downloadonly --nogpgcheck
dnf -yC distro-sync --nogpgcheck || true

dnf -y install psmisc gdb valgrind git vim emacs-nox tmux systemtap gdb \
    strace nmap ltrace lsof krb5-{libs,server,workstation} ipa-server{,-dns} \
    ccache
dnf -y debuginfo-install krb5-{libs,workstation,server} libkadm5

date > /etc/vagrant_provisioned_at
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "fedora/34-cloud-base"

    config.vm.provision "shell", inline: $script

    config.vm.define "rawhide" do |rawhide|
        rawhide.vm.provider :libvirt do |domain|
            domain.cpus = 4
            domain.graphics_type = "spice"
            domain.memory = 2048
            domain.video_type = "qxl"
            domain.random :model => "random"
            domain.volume_cache = "unsafe"
            domain.nic_model_type = "rtl8139"
        end
    end
end
